# group_vars/db_vars.yaml
packages:
  - epel-release
  - git
  - zip
  - unzip
  - python-PyMySQL
  - python3-PyMySQL
  - mariadb-server

git_repo: "https://github.com/hkhcoder/vprofile-project.git"
git_dest: "/tmp/vprofile-project"
git_version: "main"

mysql_commands: |
  sudo mysqladmin -u root password "{{ database_pass }}"
  sudo mysql -u root -p"{{ database_pass }}" -e "UPDATE mysql.user SET Password=PASSWORD('{{ database_pass }}') WHERE User='root'"
  sudo mysql -u root -p"{{ database_pass }}" -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"
  sudo mysql -u root -p"{{ database_pass }}" -e "DELETE FROM mysql.user WHERE User=''"
  sudo mysql -u root -p"{{ database_pass }}" -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%'"
  sudo mysql -u root -p"{{ database_pass }}" -e "FLUSH PRIVILEGES"
  sudo mysql -u root -p"{{ database_pass }}" -e "create database accounts"
  sudo mysql -u root -p"{{ database_pass }}" -e "grant all privileges on accounts.* TO 'admin'@'localhost' identified by 'admin123'"
  sudo mysql -u root -p"{{ database_pass }}" -e "grant all privileges on accounts.* TO 'admin'@'%' identified by 'admin123'"
  sudo mysql -u root -p"{{ database_pass }}" accounts < /tmp/vprofile-project/src/main/resources/db_backup.sql
  sudo mysql -u root -p"{{ database_pass }}" -e "FLUSH PRIVILEGES"

database_pass: "admin123"
