- hosts: dbservers
  become: true
  vars_files:
    - group_vars/db_vars.yaml

  tasks:
    - name: Update and install required packages
      package:
        name: "{{ packages }}"
        state: present
      tags:
        - packages

    - name: Start and enable MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes
      tags:
        - mariadb

    - name: Clone repository
      git:
        repo: "{{ git_repo }}"
        dest: "{{ git_dest }}"
        version: "{{ git_version }}"
      tags:
        - repository

    - name: Set MySQL root user password and cleanup
      shell: "{{ mysql_commands }}"
      tags:
        - mysql_tasks

    - name: Restart MariaDB service
      service:
        name: mariadb
        state: restarted
      tags:
        - mariadb_restart
